import type { Metadata } from 'next'
import { Manrope, Mulish } from 'next/font/google'
import './styles/globals.css'
import './styles/_normalize.css'

const manrope = Manrope(
  {
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-manrope',
  }
)

const mulish = Mulish(
  {
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-mulish',
  }
)

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${mulish.variable} ${manrope.variable} font-sans`}>
      <body>{children}</body>
    </html>
  )
}
