import { type Metadata, NextPage } from "next";
import { Locales } from "@/types";
import { getTranslation, getAllTranslations } from "@/utils/dictionary";
import Heading from "@/app/(landing)/[lang]/blog/components/Heading/Heading";
import Container from "@/components/Container";
import ArticlesList from "@/app/(landing)/[lang]/blog/components/ArticlesList/ArticlesList";
import "./styles.css";

interface IProps {
  params: {
    lang: Locales;
  };
}

export const metadata: Metadata = {
  title: "Blog Page",
  description: "Generated by create next app",
};

const BlogPage: NextPage<IProps> = async ({ params: { lang } }) => {
  const language = await getAllTranslations(lang);
  const t = getTranslation(language);

  return (
    <section className="wrapper">
      <Container className="blog">
        <Heading data={t("blog")} />
        <ArticlesList lang={lang} />
      </Container>
    </section>
  );
};

export default BlogPage;
