import { ReactNode } from "react";
import { NextPage } from "next";
import type { Metadata } from "next";
import { Manrope, Mulish } from "next/font/google";
import { Footer } from "@/components";
import "../../styles/globals.css";
import "../../styles/_normalize.css";
import { Locales } from "@/types";
import { getAllTranslations, getTranslation } from "@/utils/dictionary";
import Header from "@/components/Header";

const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-manrope",
});

const mulish = Mulish({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-mulish",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface IProps {
  children: ReactNode | ReactNode[];
  params: {
    lang: Locales;
  };
}

const RootLayout: NextPage<IProps> = async ({ params: { lang }, children }) => {
  const language = await getAllTranslations(lang);
  const t = getTranslation(language);

  return (
    <html
      lang="uk"
      className={`${mulish.variable} ${manrope.variable} font-sans`}
    >
      <body>
        <Header data={t("nav")} lang={lang} />
        <main>{children}</main>
        <Footer data={t("footer")} />
      </body>
    </html>
  );
};

export default RootLayout;
